title: Dialy Log
email: hayoungj0710@gmail.com
description: 공부한 내용을 간단하게 기록하는 블로그입니다.
author: Hayoung Jeon
baseurl: '/'
url: 'https://hayoungj.github.io'

# Social Profiles
github_username: HayoungJ
careerly_userkey: 503300

# Build settings
markdown: kramdown
paginate: 5
paginate_path: '/posts/page:num/'
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
kramdown:
  input: GFM
  syntax_highlighter: rouge
